export const Postss = [
    {
        id:1,
        description: "Love for all",
        image:"assets/",
        date:"5 min ago",
        userId: 1,
        like: 54,
        comments:9,
    },
    {
        id:2,
        description: "Love for all",
        image:"assets/",
        date:"15 min ago",
        userId: 2,
        like: 34,
        comments:19,
    },
    {
        id:3,
        description: "Love for all",
        image:"assets/",
        date:"10 min ago",
        userId: 3,
        like: 115,
        comments:90,
    },
    {
        id:4,
        description: "Love for all",
        image:"assets/",
        date:"25 min ago",
        userId: 4,
        like: 34,
        comments:29,
    },
    {
        id:5,
        description: "Love for all",
        image:"assets/",
        date:"50 min agp",
        userId: 5,
        like: 54,
        comments:69,
    },
    {
        id:6,
        description: "Love for all",
        image:"assets/",
        date:"19 min agp",
        userId: 6,
        like: 54,
        comments:18,
    },
    {
        id:7,
        description: "Love for all",
        image:"assets/",
        date:"8 min agp",
        userId: 7,
        like: 13,
        comments:7,
    },
    {
        id:8,
        description: "Love for all",
        image:"assets/",
        date:"38 min agp",
        userId: 8,
        like: 45,
        comments:34,
    }
];